### ISSUE TITLE
Stay up to date

### ISSUE THREAD

**Issue by lovetox** [malja/zroya#8]
Sorry for opening a issue about it, but do you have a blog or website where i can stay up to date with the development? For example when you think its ready for testing.

Specially interested int the zroya2 branch. Thanks

**Comment by malja** [comment]
Hi @lovetox,
no problem. On the contrary, I am very happy someone is really interested in this project.

There is a wiki page https://github.com/malja/zroya/wiki/Home-Page for this project. I will add future changes into it. 

Hope this helps with staying up to date with the project development.

**Comment by lovetox** [comment]
Thanks
